name: "test"
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Verify repository integrity
        uses: tum-esm/em27-metadata@v1.0.0-rc.11
