name: Validate metadata

on: push

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Validate EM27 metadata
        uses: tum-esm/em27-retrieval-pipeline/.github/actions/validate-metadata@v1.11.1
